#!/usr/bin/env python
import Requirements
import argparse
import pprint
import os.path

args_parser = argparse.ArgumentParser(description = "Manage requirements, generates documents.")
args_parser.add_argument('req_files', nargs="*", type=str, help="Test file")
args_parser.add_argument('-d', '--dependencies', action='store_const', const=True, default=False, help="Produce the dependency.dot graph file.")

args = args_parser.parse_args()

state = Requirements.ReqState({}, [])

for f in args.req_files:
    if os.path.isdir(f):
        Requirements.parse_directory(f, state)
    else:
        Requirements.parse_recursive(f, state)

if args.dependencies:
    with open("deps.dot", 'w') as dep_file:
        outlines = Requirements.dotify(state)
        dep_file.write("\n".join(outlines))
    pass
    
